import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import Header from "../components/header";

const Home: NextPage = () => {
  const router = useRouter();
  const createCards = () => {
    let resp: any = [];
    for (let i = 0; i < 16; i++) {
      resp.push(
        <div
          onClick={() => {
            router.push("/" + i);
          }}
          style={{
            cursor: "pointer",
            width: "25%",
            height: 223,
            padding: 10,
            display: "flex",
            flexDirection: "column",
          }}
        >
          <label style={{ font: "normal normal bold 17px/22px Segoe UI" }}>
            Ferrari
          </label>
          <label>CALIFORNIA</label>
          <img
            src="https://www.seekpng.com/png/full/68-687092_ferrari-png-free-download-2018-ferrari-488-gtb.png"
            height="100"
          />
          <div style={{ display: "flex", justifyContent: "flex-end" }}>
            <label style={{ font: "normal normal bold 24px/32px Segoe UI" }}>
              $725
              <span style={{ font: "normal normal 400 14px/19px Segoe UI" }}>
                /day
              </span>
            </label>
          </div>
        </div>
      );
    }
    return resp;
  };

  return (
    <div style={{ flex: 1, paddingLeft: "8%", paddingRight: "8%" }}>
      <Head>
        <title>Exotic Cars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <div
        style={{
          display: "flex",
          flexDirection: "row",
          flexWrap: "wrap",
          marginBottom: 57,
          marginTop: 25,
        }}
      >
        {createCards()}
      </div>
    </div>
  );
};

export default Home;
